<template>
  <div class="login-page">
    <section class="login-visual"><img class="login-logo" src="/new_logo.jpeg" alt="CONCN DataHub"><div><span>RESEARCHER ACCESS</span><h1>保存你的流域检索<br>与数据任务</h1><p>内部测试阶段仅向项目成员开放账号服务。</p></div><img class="login-map" src="/logo.png" alt="中国水文地形图"></section>
    <section class="login-form-wrap"><form @submit.prevent="submit"><header><span>{{ mode==='login'?'欢迎回来':'申请测试账号' }}</span><p>{{ mode==='login'?'登录后继续使用数据平台':'填写基本信息，我们会在审核后联系你' }}</p></header><div class="login-tabs"><button type="button" :class="{active:mode==='login'}" @click="mode='login'">登录</button><button type="button" :class="{active:mode==='register'}" @click="mode='register'">申请账号</button></div><label>用户名<input v-model="form.username" required placeholder="请输入用户名"></label><label v-if="mode==='register'">学校邮箱<input v-model="form.email" type="email" required placeholder="name@university.edu"></label><label>密码<input v-model="form.password" type="password" required minlength="6" placeholder="至少 6 位字符"></label><p v-if="message" class="form-message">{{ message }}</p><button class="submit-button">{{ mode==='login'?'登录 DataHub':'提交申请' }}<span>→</span></button><small>当前为前端演示，不会发送或保存你填写的信息。</small></form></section>
  </div>
</template>
<script setup>
import { reactive,ref } from 'vue'
const mode=ref('login'),message=ref(''),form=reactive({username:'',email:'',password:''})
function submit(){message.value='演示操作已完成，当前未连接账号服务。'}
</script>
<style scoped>
.login-page{min-height:calc(100vh - 78px);display:grid;grid-template-columns:1.1fr .9fr;background:white}.login-visual{position:relative;padding:45px clamp(28px,5vw,76px);overflow:hidden;display:flex;flex-direction:column;background:linear-gradient(145deg,#eaf8fd,#f8fcfe)}.login-logo{width:190px;height:65px;object-fit:contain}.login-visual>div{position:relative;z-index:2;margin:auto 0}.login-visual>div span{color:var(--blue);font-family:var(--mono);font-size:9px;font-weight:700;letter-spacing:.13em}.login-visual h1{margin:13px 0;color:var(--navy);font-family:var(--display);font-size:clamp(38px,4vw,58px);font-weight:600;line-height:1.16;letter-spacing:-.04em}.login-visual p{color:var(--muted);font-size:12px}.login-map{position:absolute;right:-13%;bottom:-15%;width:70%;opacity:.19;filter:saturate(.7)}.login-form-wrap{padding:45px;display:grid;place-items:center}.login-form-wrap form{width:min(390px,100%)}.login-form-wrap header span{color:var(--navy);font-family:var(--display);font-size:26px;font-weight:600}.login-form-wrap header p{margin:7px 0 0;color:var(--muted);font-size:11px}.login-tabs{margin:34px 0 25px;display:flex;border-bottom:1px solid var(--line)}.login-tabs button{position:relative;padding:0 3px 12px;margin-right:27px;border:0;color:#91a4b0;background:transparent;cursor:pointer;font-size:12px}.login-tabs button.active{color:var(--blue);font-weight:600}.login-tabs button.active:after{content:'';position:absolute;left:0;right:0;bottom:-1px;height:2px;background:var(--blue)}label{display:block;margin-top:17px;color:#4c687c;font-size:10px;font-weight:600}input{width:100%;height:44px;margin-top:8px;padding:0 12px;border:1px solid var(--line);border-radius:9px;outline:0;color:var(--navy);background:var(--snow);font-size:11px}input:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(22,139,224,.08)}.submit-button{width:100%;height:45px;margin-top:24px;padding:0 15px;display:flex;align-items:center;justify-content:space-between;border:0;border-radius:9px;color:white;background:linear-gradient(90deg,var(--blue),#20a9d2);cursor:pointer;font-size:11px;font-weight:600}.login-form-wrap form>small{display:block;margin-top:12px;color:#9aabb6;text-align:center;font-size:8px}.form-message{padding:9px;border-radius:7px;color:#16875f;background:#edf9f4;font-size:9px}@media(max-width:760px){.login-page{grid-template-columns:1fr}.login-visual{display:none}.login-form-wrap{padding:45px 22px}}
</style>
